1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim. 
-> Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [2]:
import numpy as np

array = np.array([1,2,3,4,5],dtype="int")
print(f"Arrayin tipi={array.dtype}")
print(f"Arrayin boyutu={array.ndim}")
print(f"Arrayin eleman sayisi={array.size}")

Arrayin tipi=int64
Arrayin boyutu=1
Arrayin eleman sayisi=5


In [7]:
import numpy as np

array2d = np.array([[1,2,6,7],
                    [4,3,9,5]])

print("Iki Boyutlu Array")
print(f"Tipi={array2d.dtype}")
print(f"Boyutu (ndim)={array2d.ndim}")
print(f"Shape (satir, sutun)={array2d.shape}")
print(f"Eleman sayisi={array2d.size}")
print(f"Satir sayisi={array2d.shape[0]}")
print(f"Sutun sayisi={array2d.shape[1]}")

array3d = np.array([[[7,5,14],[21,8,11]],
                    [[8,6,20],[14,3,9]]])

print("\nUc Boyutlu Array")
print(f"Tipi={array3d.dtype}")
print(f"Boyutu (ndim)={array3d.ndim}")
print(f"Shape (katman, satir, sutun)={array3d.shape}")
print(f"Eleman sayisi={array3d.size}")
print(f"Katman sayisi={array3d.shape[0]}")
print(f"Satir sayisi (her katmanda)={array3d.shape[1]}")
print(f"Sutun sayisi (her satirda)={array3d.shape[2]}")

Iki Boyutlu Array
Tipi=int64
Boyutu (ndim)=2
Shape (satir, sutun)=(2, 4)
Eleman sayisi=8
Satir sayisi=2
Sutun sayisi=4

Uc Boyutlu Array
Tipi=int64
Boyutu (ndim)=3
Shape (katman, satir, sutun)=(2, 2, 3)
Eleman sayisi=12
Katman sayisi=2
Satir sayisi (her katmanda)=2
Sutun sayisi (her satirda)=3


3.İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [10]:
import numpy as np

arr2=np.array([[1,2,6,7],[4,3,9,5]])

arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

print("2D arraydeki 2=",arr2[0][1])
print("2D arraydeki 7=",arr2[0][3])

print("3D arraydeki 9=",arr3[1][1][2])
print("3D arraydeki 5=",arr3[0][0][1])

2D arraydeki 2= 2
2D arraydeki 7= 7
3D arraydeki 9= 9
3D arraydeki 5= 5


4.Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [9]:
import numpy as np

arr2=np.array([[1,2,6,7],[4,3,9,5]])

arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

print("2D arraydeki 2,6=",arr2[0,1:3])      
print("2D arraydeki 3,9,5=",arr2[1,1:4])  

print("3D arraydeki 21,8,11=",arr3[0,1,:])
print("3D arraydeki 6,20=",arr3[1,0,1:3]) 

2D arraydeki 2,6= [2 6]
2D arraydeki 3,9,5= [3 9 5]
3D arraydeki 21,8,11= [21  8 11]
3D arraydeki 6,20= [ 6 20]


5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [11]:
import numpy as np

sifirlar = np.zeros((5,3),dtype="int")
birler = np.ones((5,3),dtype="int")

print(f"Sifirlardan olusan array\n{sifirlar}")
print(f"\nBirlerden olusan array\n{birler}")

satir_birlestirmesi = np.concatenate([sifirlar,birler])
print(f"Satirlarin birlestirildigi durum\n{satir_birlestirmesi}\n")

sutun_birlestirmesi = np.concatenate([sifirlar,birler],axis=1)
print(f"Sutunlarin birlestirildigi durum\n{sutun_birlestirmesi}\n")


Sifirlardan olusan array
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Birlerden olusan array
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Satirlarin birlestirildigi durum
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sutunlarin birlestirildigi durum
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]

